### ISSUE TITLE
Random Errors

### ISSUE THREAD

**Issue by madtomic** [mcMMO-Dev/mcMMO-extras#1]
Random errors on console.

[22:34:41 WARN]: java.lang.NullPointerException [22:34:41 WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native M ethod) [22:34:41 WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown S ource) [22:34:41 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unkno wn Source) [22:34:41 WARN]: at java.lang.reflect.Method.invoke(Unknown Source) [22:34:41 WARN]: at me.Xeroun.McMExtras.ExpBar.FakeDragon.sendDestroyPack et(FakeDragon.java:111) [22:34:41 WARN]: at me.Xeroun.McMExtras.ExpBar.FakeDragon.setBossBar(Fake Dragon.java:122) [22:34:41 WARN]: at me.Xeroun.McMExtras.PlayerData$1.run(PlayerData.java: 27) [22:34:41 WARN]: at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftTask.ru n(CraftTask.java:71) [22:34:41 WARN]: at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftSchedul er.mainThreadHeartbeat(CraftScheduler.java:346) [22:34:41 WARN]: at net.minecraft.server.v1_7_R3.MinecraftServer.v(Minecr aftServer.java:638) [22:34:41 WARN]: at net.minecraft.server.v1_7_R3.DedicatedServer.v(Dedica tedServer.java:284) [22:34:41 WARN]: at net.minecraft.server.v1_7_R3.MinecraftServer.u(Minecr aftServer.java:584) [22:34:41 WARN]: at net.minecraft.server.v1_7_R3.MinecraftServer.run(Mine craftServer.java:490) [22:34:41 WARN]: at net.minecraft.server.v1_7_R3.ThreadServerApplication. run(SourceFile:628) [22:34:42 WARN]: java.lang.NullPointerException [22:34:42 WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native M ethod) [22:34:42 WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown S ource) [22:34:42 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unkno wn Source) [22:34:42 WARN]: at java.lang.reflect.Method.invoke(Unknown Source) [22:34:42 WARN]: at me.Xeroun.McMExtras.ExpBar.FakeDragon.sendDestroyPack et(FakeDragon.java:111) [22:34:42 WARN]: at me.Xeroun.McMExtras.ExpBar.FakeDragon.setBossBar(Fake Dragon.java:122) [22:34:42 WARN]: at me.Xeroun.McMExtras.PlayerData$1.run(PlayerData.java: 27) [22:34:42 WARN]: at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftTask.ru n(CraftTask.java:71) [22:34:42 WARN]: at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftSchedul er.mainThreadHeartbeat(CraftScheduler.java:346) [22:34:42 WARN]: at net.minecraft.server.v1_7_R3.MinecraftServer.v(Minecr aftServer.java:638) [22:34:42 WARN]: at net.minecraft.server.v1_7_R3.DedicatedServer.v(Dedica tedServer.java:284) [22:34:42 WARN]: at net.minecraft.server.v1_7_R3.MinecraftServer.u(Minecr aftServer.java:584) [22:34:42 WARN]: at net.minecraft.server.v1_7_R3.MinecraftServer.run(Mine craftServer.java:490) [22:34:42 WARN]: at net.minecraft.server.v1_7_R3.ThreadServerApplication. run(SourceFile:628) [22:34:50 WARN]: java.lang.NullPointerException [22:34:50 WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native M ethod) [22:34:50 WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown S ource) [22:34:50 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unkno wn Source) [22:34:50 WARN]: at java.lang.reflect.Method.invoke(Unknown Source) [22:34:50 WARN]: at me.Xeroun.McMExtras.ExpBar.FakeDragon.sendDestroyPack et(FakeDragon.java:111) [22:34:50 WARN]: at me.Xeroun.McMExtras.ExpBar.FakeDragon.setBossBar(Fake Dragon.java:122) [22:34:50 WARN]: at me.Xeroun.McMExtras.PlayerData$1.run(PlayerData.java: 27) [22:34:50 WARN]: at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftTask.ru n(CraftTask.java:71) [22:34:50 WARN]: at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftSchedul er.mainThreadHeartbeat(CraftScheduler.java:346) [22:34:50 WARN]: at net.minecraft.server.v1_7_R3.MinecraftServer.v(Minecr aftServer.java:638) [22:34:50 WARN]: at net.minecraft.server.v1_7_R3.DedicatedServer.v(Dedica tedServer.java:284) [22:34:50 WARN]: at net.minecraft.server.v1_7_R3.MinecraftServer.u(Minecr aftServer.java:584) [22:34:50 WARN]: at net.minecraft.server.v1_7_R3.MinecraftServer.run(Mine craftServer.java:490) [22:34:50 WARN]: at net.minecraft.server.v1_7_R3.ThreadServerApplication. run(SourceFile:628) [22:34:51 WARN]: java.lang.NullPointerException [22:34:51 WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native M ethod) [22:34:51 WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown S ource) [22:34:51 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unkno wn Source) [22:34:51 WARN]: at java.lang.reflect.Method.invoke(Unknown Source) [22:34:51 WARN]: at me.Xeroun.McMExtras.ExpBar.FakeDragon.sendDestroyPack et(FakeDragon.java:111) [22:34:51 WARN]: at me.Xeroun.McMExtras.ExpBar.FakeDragon.setBossBar(Fake Dragon.java:122) [22:34:51 WARN]: at me.Xeroun.McMExtras.PlayerData$1.run(PlayerData.java: 27) [22:34:51 WARN]: at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftTask.ru n(CraftTask.java:71) [22:34:51 WARN]: at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftSchedul er.mainThreadHeartbeat(CraftScheduler.java:346) [22:34:51 WARN]: at net.minecraft.server.v1_7_R3.MinecraftServer.v(Minecr aftServer.java:638) [22:34:51 WARN]: at net.minecraft.server.v1_7_R3.DedicatedServer.v(Dedica tedServer.java:284) [22:34:51 WARN]: at net.minecraft.server.v1_7_R3.MinecraftServer.u(Minecr aftServer.java:584) [22:34:51 WARN]: at net.minecraft.server.v1_7_R3.MinecraftServer.run(Mine craftServer.java:490) [22:34:51 WARN]: at net.minecraft.server.v1_7_R3.ThreadServerApplication. run(SourceFile:628)

**Comment by TfT-02** [comment]
Wrong mcMMO-Extras, this should be reported to the author of http://dev.bukkit.org/bukkit-plugins/mcmmoextras/ and not us.

mcMMO-Extras from the mcMMO dev team was a command line tool for admins, but it hasn't been updated in the past 3 years.
